# Generated by Django 3.1.4 on 2020-12-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, unique=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '广告组管理',
                'verbose_name_plural': '广告组管理',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Tag', max_length=50, unique=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag管理',
                'verbose_name_plural': 'Tag管理',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, verbose_name='标题')),
                ('start_time', models.DateTimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间', verbose_name='结束时间')),
                ('redirect', models.CharField(help_text='跳转地址', max_length=255, verbose_name='跳转地址')),
                ('img', models.ImageField(blank=True, help_text='广告图片', null=True, upload_to='', verbose_name='广告图片')),
                ('sort', models.IntegerField(default=1000, help_text='数字越小，排名越靠前', verbose_name='排序ID')),
                ('num', models.IntegerField(default=0, help_text='阅读量', verbose_name='阅读量')),
                ('group', models.ForeignKey(help_text='所属广告组', on_delete=django.db.models.deletion.PROTECT, related_name='rn_ads_group', to='app_ad.group', verbose_name='所属广告组')),
            ],
            options={
                'verbose_name': '广告管理',
                'verbose_name_plural': '广告管理',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
