# Generated by Django 2.2.5 on 2020-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('-pk',), 'verbose_name': '回滚', 'verbose_name_plural': '回滚'},
        ),
    ]
