# Generated by Django 3.1.4 on 2020-12-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='报告时间', unique=True, verbose_name='报告时间')),
                ('views', models.IntegerField(default=1, help_text='浏览量', verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '数据报告',
                'verbose_name_plural': '数据报告',
            },
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='静态内容')),
            ],
            options={
                'verbose_name': '静态数据',
                'verbose_name_plural': '静态数据',
                'ordering': ['id'],
            },
        ),
    ]
